package.json
src/daemon.js
src/utils.js
test/connect/go2go.js
test/connect/js2js.js

`js-libp2p-daemon` and `js-libp2p-daemon-client` were updated. Now, we use `multiaddr` to connect the daemon with the client instead of the socket path.

chore: update daemon and daemon-client

---

src/daemon.js
test/connect/go2go.js
test/connect/go2js.js
test/connect/js2go.js
test/connect/js2js.js
test/utils/spawnDaemons.js

Refactor for having a spawn daemons utility, as well as allow to pass options for starting a daemon.
This code is currently replicated in the `dht` and `pubsub` PRs and it is also needed for the `circuit` and `stream` tests.

chore: spawn daemons utility and start options

---

.travis.yml

Removing commitlint in favor of squash merge commit cleaning. This removes a barrier to entry for new contributors creating PRs and having those PRs run CI tests

chore: remove commitlint

---

src/daemon.js
test/connect/go2js.js

Add test for connecting Go to JS peer with Secp256k1 keys.
Follow-up to #21, so please merge that first.

Test connecting Go to JS peer with Secp256k1 keys

---

package.json
src/daemon.js

This PR updates the `js-libp2p` to the new version after the async refactor.
It also sends the process stdout logs to the `daemon` debug now.
Needs:

chore: update deps

---

package.json

Add interop release scripts, so that we start releasing this module to be used as a `devDependency` in `js-libp2p`. This allows us to run interop tests on `js-libp2p` CI, in the same way as `js-ipfs` is doing.
Needs to be released, so that `js-libp2p` can use it
Needs

chore: add release scripts

---

README.md
package.json
src/daemon.js
src/utils.js
test/connect/ed25519/go2js.js
test/connect/ed25519/index.js
test/connect/ed25519/js2go.js
test/connect/rsa/go2js.js
test/connect/rsa/index.js
test/connect/rsa/js2go.js
test/connect/secp256k1/go2js.js
test/connect/secp256k1/index.js
test/connect/secp256k1/js2go.js

This PR replaces #32 for adding interop tests for secio and noise, since after #37 being merged using a folder structure with each key, the #32 PR got a complex task to rebase.
This PR adds exactly the same as #32 
- The connect tests can now be run with different configurations to make it easier to run those suites for both secio and noise.
- Enabled the ability to specify local daemons when running the tests to make verifying go daemon changes easier. Doing this is noted in the readme.

feat: add connect tests using secio and noise

---

package.json
test/dht/peer-routing/go2go.js
test/dht/peer-routing/go2js.js
test/dht/peer-routing/js2go.js
test/dht/peer-routing/js2js.js

In the context of the PeerStore improvements specified on [libp2p/js-libp2p#582](https://github.com/libp2p/js-libp2p/issues/582) and as a follow up of [libp2p/js-libp2p#590](https://github.com/libp2p/js-libp2p/pull/590).
This PR contains two commits, one for updating the `peer-store` API and a second one to use the new `libp2p` API with no `peer-info`
The modules changed (`libp2p` and `libp2p-kad-dht`) were updated.
Needs:

chore: update libp2p daemon with peer-store

---

src/utils.js

This switches the test daemons to default to running noise instead of secio. Basic connection tests for the 3 key types are still being run for both secio and noise.
Ref:
go-libp2p defaulting to Noise https://github.com/libp2p/go-libp2p/pull/972

test: default to noise in tests

---

.travis.yml
package.json
pdd/PDD-THE-IPFS-BUNDLE.md
src/daemon.js
src/utils.js
test/connect/ed25519/index.js
test/connect/rsa/index.js
test/connect/secp256k1/index.js

Secio has now been completely deprecated and support has been removed from the go-libp2p daemon (in master).
Needs:

feat: remove secio support

---

package.json
src/index.ts
src/streams/echo.ts
src/streams/index.ts

Adds a simple test that ensures we can send and receive data from peers.
BREAKING CHANGE: requires yamux and mplex

feat!: add stream tests

---

package.json

`multiformats@11.x.x` shipped with a [breaking change](https://github.com/multiformats/js-multiformats/pull/230) so update all deps using multiformats to the latest version.
Blocked By: https://github.com/libp2p/js-libp2p-daemon/pull/170

deps!: Update multiformats and related dependencies

---

package.json
src/pubsub/floodsub.ts
src/pubsub/gossipsub.ts
src/pubsub/hybrid.ts

Instead of waiting for 800ms for pubsub subscriptions to propagate, wait for the publisher to see the receiver in it's list of subscribers for a given topic.
This is because sometimes in CI it can taker longer than 800ms for the subs list to update which causes the tests to be flaky.

fix: remove timeouts from pubsub tests

---

src/pubsub/floodsub.ts
src/pubsub/gossipsub.ts
src/pubsub/hybrid.ts
src/pubsub/utils.ts

Follow up to #88 - instead wait for both peers to see each other in their subscribed peers list.

fix: wait for both peers to see each other in topic peer lists

---

package.json
src/pubsub/floodsub.ts
src/pubsub/gossipsub.ts
src/pubsub/hybrid.ts
src/pubsub/utils.ts

Updates to latest @libp2p/daemon-client to allow subscribing to topics separately from consuming their messages.
BREAKING CHANGE: requires new daemon client version

fix!: subscribe to topic separately from consuming messages

---

package.json
src/pubsub/floodsub.ts
src/pubsub/gossipsub.ts
src/pubsub/hybrid.ts
src/pubsub/utils.ts

Only wait for the sending peer to see the remote in their topic subscriber list but also wait a little bit longer for gossipsub to rebalance the mesh to increase the chances of the publisher actually sending a pubsub message to the subscriber.

fix: wait for gossipsub heartbeat before sending message

---

package.json
src/connect.ts
src/dht/content-fetching.ts
src/dht/content-routing.ts
src/dht/peer-routing.ts
src/pubsub/floodsub.ts
src/pubsub/gossipsub.ts
src/pubsub/hybrid.ts
src/pubsub/utils.ts
src/relay/index.ts
src/streams/echo.ts

We store references to the daemon client in the return value of `Promise.all` and use them to stop the daemons after a test run - if one or more daemons fail to start, we lose all references to daemons that started successfully so cannot stop them and the test run hangs.
Instead start them individually so we can tear down any that started successfully.
Refs: libp2p/js-libp2p#1575

fix: start daemons in series

---

package.json
src/connect.ts
src/dht/content-fetching.ts
src/dht/content-routing.ts
src/dht/index.ts
src/dht/peer-routing.ts
src/index.ts
src/pubsub/floodsub.ts
src/pubsub/gossipsub.ts
src/pubsub/hybrid.ts
src/pubsub/index.ts
src/pubsub/utils.ts
src/relay/index.ts
src/relay/util.ts
src/streams/echo.ts
src/utils/dht-record.ts

Updates all deps to versions that gracefully close streams.
BREAKING CHANGE: requires libp2p@0.46.x or later

fix!: gracefully close streams

---

src/connect.ts
src/index.ts
src/relay/index.ts
src/streams/echo.ts
src/streams/index.ts
src/utils/test-matrix.ts

Adds tests for tls encryption but as a major to control when it is pulled in to the js-libp2p monorepo.
BREAKING CHANGE: tls support is required

feat!: test tls encryption

---

src/dht/content-fetching.ts

If the `before` step times out, `nodes` may not be set.

fix: guard on nodes
